# Generated by Django 3.2.8 on 2021-10-09 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bucquage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('nom_produit', models.CharField(max_length=50)),
                ('prix_produit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('entite_produit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Consommateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('raccourci', models.CharField(max_length=3)),
                ('entite', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=200)),
                ('accepted', models.BooleanField(default=False)),
                ('crediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_crediteur', to='appkfet.consommateur')),
                ('debiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_debiteur', to='appkfet.consommateur')),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=5)),
                ('methode', models.CharField(choices=[('CB', 'Carte bleue'), ('Espèces', 'Espèces'), ('Chèque', 'Chèque'), ('Lydia', 'Lydia')], max_length=50)),
                ('solde_before', models.DecimalField(decimal_places=2, max_digits=5)),
                ('solde_after', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cible_recharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkfet.consommateur')),
            ],
        ),
    ]
