# Generated by Django 4.0.3 on 2022-07-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucquage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('nom_produit', models.CharField(max_length=50)),
                ('prix_produit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('entite_produit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Consommateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('totaldep', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('activated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=5)),
                ('methode', models.CharField(choices=[('CB', 'Carte bleue'), ('Espèces', 'Espèces'), ('Chèque', 'Chèque'), ('Lydia', 'Lydia')], max_length=50)),
                ('solde_before', models.DecimalField(decimal_places=2, max_digits=5)),
                ('solde_after', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cible_recharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkfet.consommateur')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('raccourci', models.CharField(max_length=3)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_evenement', models.CharField(max_length=200)),
                ('prix_evenement', models.DecimalField(decimal_places=2, max_digits=5)),
                ('entite_evenement', models.CharField(max_length=200)),
                ('date_evenement', models.DateTimeField()),
                ('cible_evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkfet.consommateur')),
            ],
        ),
    ]
