# Generated by Django 3.2.8 on 2021-10-09 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('appkfet', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='entite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
