# Generated by Django 4.0.3 on 2022-06-15 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appkfet', '0004_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('date_ouverture', models.DateTimeField()),
                ('date_fermeture', models.DateTimeField()),
                ('date_event', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('obligatoire', models.BooleanField(default=False)),
                ('parent_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkfet.events')),
            ],
        ),
        migrations.CreateModel(
            name='Participation_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('participation_ok', models.BooleanField(default=False)),
                ('cible_participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkfet.consommateur')),
                ('product_participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkfet.product_events')),
            ],
        ),
    ]
