# Generated by Django 4.0.3 on 2022-06-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appkfet', '0005_events_product_events_participation_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation_event',
            name='cible_participation',
        ),
        migrations.RemoveField(
            model_name='participation_event',
            name='product_participation',
        ),
        migrations.RemoveField(
            model_name='product_events',
            name='parent_event',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Participation_event',
        ),
        migrations.DeleteModel(
            name='Product_events',
        ),
    ]
