# Generated by Django 4.0.3 on 2022-06-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkfet', '0006_remove_participation_event_cible_participation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommateur',
            name='totaldep',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
