# Generated by Django 4.0.3 on 2022-06-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appkfet', '0008_consommateur_activated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
