# Generated by Django 4.0.3 on 2022-06-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkfet', '0009_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommateur',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='consommateur',
            name='totaldep',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
    ]
