# Generated by Django 4.0.3 on 2022-07-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('cansubscribe', models.BooleanField(default=True, verbose_name="Ouvert à l'inscription")),
                ('date_event', models.DateTimeField()),
                ('ended', models.BooleanField(default=False, verbose_name='Evènement terminé')),
            ],
        ),
        migrations.CreateModel(
            name='Participation_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='Quantité')),
                ('participation_ok', models.BooleanField(default=False)),
                ('participation_bucquee', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('obligatoire', models.BooleanField(default=False)),
                ('parent_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevents.event')),
            ],
        ),
    ]
