# Generated by Django 4.0.3 on 2022-07-05 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appkfet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appevents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation_event',
            name='cible_participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkfet.consommateur'),
        ),
        migrations.AddField(
            model_name='participation_event',
            name='product_participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevents.product_event'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
    ]
