# Generated by Django 4.0.3 on 2022-06-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appevents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Product_events',
            new_name='Product_event',
        ),
    ]
