# Generated by Django 4.0.3 on 2022-06-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevents', '0002_rename_events_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_fermeture',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_ouverture',
            field=models.DateField(),
        ),
    ]
