# Generated by Django 4.0.3 on 2022-06-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevents', '0003_alter_event_date_fermeture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_fermeture',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_ouverture',
        ),
        migrations.AddField(
            model_name='event',
            name='cansubscribe',
            field=models.BooleanField(default=True),
        ),
    ]
