# Generated by Django 4.0.3 on 2022-06-17 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
        ('appevents', '0006_alter_event_cansubscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appuser.utilisateur'),
            preserve_default=False,
        ),
    ]
