# Generated by Django 3.2.8 on 2021-10-09 17:21

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('chambre', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=10, verbose_name='Téléphone')),
                ('bucque', models.CharField(blank=True, max_length=200)),
                ('fams', models.CharField(blank=True, max_length=200, verbose_name="Fam's")),
                ('proms', models.CharField(blank=True, max_length=200, verbose_name="Prom's")),
                ('is_gadz', models.BooleanField(default=False)),
                ('is_conscrit', models.BooleanField(default=False)),
                ('has_cotiz', models.BooleanField(default=False)),
                ('date_expiration', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
