# Generated by Django 4.0.3 on 2022-06-20 15:13

from django.db import migrations
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0002_ldapuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapuser',
            name='full_name',
            field=ldapdb.models.fields.CharField(db_column='cn', max_length=200, primary_key=True, serialize=False),
        ),
    ]
