# Generated by Django 3.2.8 on 2021-10-09 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('mac', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='^([0-9a-f]{2}[:]){5}([0-9a-f]{2})$')])),
                ('accepted', models.BooleanField(default=False)),
                ('has_rezal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='radcheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=17)),
                ('attribute', models.CharField(default='ClearText-Password', max_length=64)),
                ('op', models.CharField(default=':=', max_length=2)),
                ('value', models.CharField(default='authok', max_length=64)),
            ],
            options={
                'db_table': 'radcheck',
            },
        ),
    ]
